### ISSUE TITLE
Install hawtio-operator with OLM

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-operator#47]
What are the recommended steps to install the operator from source with OLM?  Is it already documented somewhere?  If not, it's good idea to document it.

**Comment by astefanutti** [comment]
That's a good question :)

As of now, I think the best way to install the operator from source with OLM is to follow the procedure described at https://github.com/operator-framework/operator-registry#bundle-images. It would be very valuable to adapt it for the Hawtio operator so that it's a no brainer for newcomers.

For information, the Hawtio operator is also published at https://github.com/operator-framework/community-operators/tree/master/community-operators/hawtio-operator.
