### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by astefanutti** [hawtio/hawtio-operator#52]
We need to cut 0.4.0 to address hawtio/hawtio#2695.

**Comment by tadayosi** [comment]
I have no idea how to release hawtio-operator. If you can give me some pointer on how to release it, I can work on it. Thanks.

**Comment by astefanutti** [comment]
The release process is pushing the tag, building the container image locally, and pushing it to DockerHub. At some point, I'd vote to migrate to Quay, but that can be done for the next release.

**Comment by tadayosi** [comment]
Thanks. OK, I'm already a member of the dockerhub org, so it seems I can take care of it if you haven't done it yet.

**Comment by astefanutti** [comment]
Feel free to go ahead 👍🏼.

**Comment by tadayosi** [comment]
Released. Just FYI for podman users, we need `export BUILDAH_FORMAT=docker` or otherwise add `--format docker` when doing `docker build` so that the pushed image is shown nicely on Docker Hub.

https://hub.docker.com/layers/165703506/hawtio/operator/0.4.0/images/sha256-928a296afa1a86e652aeefdfe0c2b1726e23688ca25f5b7dc11a0077f4aa99d6
